### ISSUE TITLE
Huisstijl kleuren goed toepassen

### ISSUE THREAD

**Issue by SamaraFellaDina** [driezie/the-startup-responsive-interactieve-website#3]
In jou ontwerp gebruik je een aantal kleuren die Enrise inderdaad gebruikt, alleen worden deze als referentie naar een bedrijf gebruikt waarmee ze hebben samengewerkt

Ik heb deze `:root`

```css
:root {
    --primary-yellow: #F2A900;
    --primary-light-yellow:#FDF2D9;
    --primary-black: #000;
    --primary-white:#fff;

    --gray-light: #C8C9C7;
    --gray-regular:#75787B;
    --gray-dark:#53565A;

}
```

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbWd2Z2lpdDhqcWFyMTVvajNleXV5NjR1Y3VzdTVzdTlpcXY0dHhueCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/duNowzaVje6Di3hnOu/giphy-downsized-large.gif)
